### PR TITLE
Make AggregatedVerKey + AggregatedSignature clone

### PR DESCRIPTION
**Pull request by andrewjstone**
Allowing cloning of signatures and keys is very useful.

### CODE REVIEW

**Comment by andrewjstone** [comment]
The CI build is failing for the same reason local builds fail. The top level workspace doesn't set a curve, but when it tries to build the `amcl_rust_wrapper` dependency it tries to use the setting for both `bls381` and `secp256k1` as defined as features in the bls and musig subcrates respectively.

Unfortunately, I'm not sure how to fix this, but it's also not caused by this change.

It should be noted that building directly in the bls crate works fine.

**Comment by lovesh** [comment]
Sorry for the trouble. The CI got broken after i restructured the project. Fixed it now.

**Comment by andrewjstone** [comment]
Thanks for fixing CI  @lovesh. Can you please rerun the build and merge in the change if you agree with it?

**Comment by lovesh** [comment]
Thanks @andrewjstone for the contribution.

**Pull request merged**
